=== Tableau détaillé des tâches
////
****Note : 2 pages max - les fiches modules seront placées en annexe,
elles doivent être rédigées avec l’expert.****

Les différents aspects du projet sont découpés en tâches numérotées et
hiérarchisées (Tâches/sous-tâches, etc.). Chaque tâche est décrite
précisément et une équipe (typiquement un binôme) est affecté à sa
réalisation. Un module est typiquement constitué de plusieurs tâches et
sous-tâches. Pour le PAN3, vous aurez à démontrer une version simple,
*intégrée* et fonctionnelle de ce projet, nommée « prototype allégé ».
Dans le Tableau 1, complétez la colonne « Intégrée au PAN3 » comme
suit :

* Intégrée au PAN3 : la sous-tâche est soit finie soit en cours et
intégrée dans le prototype allégé.
* Non-intégrée au PAN3 : la sous-tâche est en cours, mais non intégrée
dans le prototype allégé, l’intégration se fera pour PAN4. L’avancement
de la sous-tâche sera donc démontré au PAN3 indépendamment du prototype
allégé (code MatLab ou autre)

Certaines sous-tâches peuvent ne pas être démontrables dans le prototype
allégé. Mettez-vous d’accord avec vos experts techniques pour savoir ce
qu’il est réaliste de démontrer au PAN3. N’hésitez pas à redécouper en 2
sous-taches, l’une démontrable au PAN3 et l’autre uniquement au PAN4.
////
[cols=",,^",options="header",]
|====
| Tâche | Description                                           | Intégré au PAN3
| T1    | Analyse de l'oeuvre                                   |
| T1.1  | Analyse de l'image                                    |
| T1.1.1| Couleurs                                              | X
| T1.1.2| Éléments (objets, personnages, ...etc)                | X
| T1.1.3| Exctraction d'un vecteur de style                     |
| T1.2  | Analyse de texte (description du Louvre)              |
| T1.2.1| Extraction des objets/personnages de la description   | X
| T1.2.2| Extraction des émotions                               |
| T2    | Création du script                                    | X
| T3    | Communication entre boitier et la base de données     |
| T3.1  | Récupération du script                                | X
| T3.2  | Récupération des sons (banque de son)                 |
| T4    | Boitier (Systèmes embarqués)                          |
| T4.1  | Vibreurs                                              | X
| T4.2  | Résistances                                           | X
| T4.3  | Module de refroidissment                              |
| T4.4  | Son (casque)                                          | X
| T5    | Interface Homme-Machine                               |
|====

* Information quant au matériel

On souhaite fabriquer un boitier qui nous permettra de faire ressentir les émotions souhaitées à l'utilisateur, nous avons ainsi besoin de *mini vibreurs* (équivalent au vibreur présent dans les smartphones), de *minis résistances* chauffantes et d'un *système de refroidissement* (on aura besoin de ventilateur et d'un système pour faire circuler l'air froid). On aura également besoin d'une surface molle qu'on pourra mettre au dessus des différents sytèmes cités précedemment qui permettra aux vibrations, à la chaleur et au froid de se propager.
Nous aurons également besoin d'une carte *arduino* pour communiquer avec les composants et un *raspberry* comme unité centrale.
Finalement il nous faut également un *serveur sous linux* pour l'analyse d'image et de texte et un *site web* contenant tous nos fichiers de configuration. 
Compte tenu de la *situation actuelle*, on aura peut-être besoin de *dupliquer le matériel* (le raspberry , les mini vibreurs et les résistances), ce qui ne pose à priori pas de problème étant donné le prix plutôt abordable de ce matériel. Nous avons envoyé un mail à notre expert système embarqué pour en savoir plus.
